# **Pandas Project - Bilnkit Sales Data Analysis**

### **Get Data into Python Program**

**Import the required libraries**

In [1]:
import pandas as pd

**Loading the data from csv file**

In [2]:
blinkit_data = pd.read_csv('Blinkit Grocery Data.csv')

**Display the first 10 rows of data**

In [3]:
blinkit_data[:10]

,Item Identifier,Item Fat Content,Item Type,Outlet Establishment Year,Outlet Location Type,Outlet Size,Outlet Type,Total Amount,Rating
0,FDX32,Regular,Fruits and Vegetables,2012,Tier 1,Medium,Supermarket Type1,13129.44365,5.0
1,NCB42,Low Fat,Health and Hygiene,2022,Tier 3,Medium,Supermarket Type2,10410.26530,5.0
2,FDR28,Regular,Frozen Foods,2010,Tier 1,Small,Supermarket Type1,14893.14525,5.0
3,FDL50,Regular,Canned,2000,Tier 3,High,Supermarket Type1,11417.04015,5.0
4,DRI25,Low Fat,Soft Drinks,2015,Tier 2,Small,Supermarket Type1,4978.31635,5.0
5,FDS52,low fat,Frozen Foods,2020,Tier 2,Small,Supermarket Type1,9241.74440,5.0
6,NCU05,Low Fat,Health and Hygiene,2011,Tier 3,Small,Grocery Store,7351.92745,5.0
7,NCD30,Low Fat,Household,2015,Tier 2,Small,Supermarket Type1,8670.55215,5.0
8,FDW20,Low Fat,Fruits and Vegetables,2000,Tier 3,High,Supermarket Type1,11206.61325,5.0
9,FDX25,Low Fat,Canned,1998,Tier 3,Medium,Supermarket Type3,16419.11030,5.0

In [4]:
blinkit_data.head(10)

,Item Identifier,Item Fat Content,Item Type,Outlet Establishment Year,Outlet Location Type,Outlet Size,Outlet Type,Total Amount,Rating
0,FDX32,Regular,Fruits and Vegetables,2012,Tier 1,Medium,Supermarket Type1,13129.44365,5.0
1,NCB42,Low Fat,Health and Hygiene,2022,Tier 3,Medium,Supermarket Type2,10410.26530,5.0
2,FDR28,Regular,Frozen Foods,2010,Tier 1,Small,Supermarket Type1,14893.14525,5.0
3,FDL50,Regular,Canned,2000,Tier 3,High,Supermarket Type1,11417.04015,5.0
4,DRI25,Low Fat,Soft Drinks,2015,Tier 2,Small,Supermarket Type1,4978.31635,5.0
5,FDS52,low fat,Frozen Foods,2020,Tier 2,Small,Supermarket Type1,9241.74440,5.0
6,NCU05,Low Fat,Health and Hygiene,2011,Tier 3,Small,Grocery Store,7351.92745,5.0
7,NCD30,Low Fat,Household,2015,Tier 2,Small,Supermarket Type1,8670.55215,5.0
8,FDW20,Low Fat,Fruits and Vegetables,2000,Tier 3,High,Supermarket Type1,11206.61325,5.0
9,FDX25,Low Fat,Canned,1998,Tier 3,Medium,Supermarket Type3,16419.11030,5.0

In [5]:
blinkit_data[-10:]

,Item Identifier,Item Fat Content,Item Type,Outlet Establishment Year,Outlet Location Type,Outlet Size,Outlet Type,Total Amount,Rating
8513,DRY23,Regular,Soft Drinks,1998,Tier 3,Medium,Supermarket Type3,3872.73580,4.0
8514,FDA11,low fat,Baking Goods,1998,Tier 3,Medium,Supermarket Type3,8550.60990,4.0
8515,FDK38,low fat,Canned,1998,Tier 3,Medium,Supermarket Type3,13462.89935,4.0
8516,FDO38,low fat,Canned,1998,Tier 3,Medium,Supermarket Type3,7129.62365,4.0
8517,FDG32,low fat,Fruits and Vegetables,1998,Tier 3,Medium,Supermarket Type3,20069.54230,4.0
8518,NCT53,low fat,Health and Hygiene,1998,Tier 3,Medium,Supermarket Type3,14850.87215,4.0
8519,FDN09,low fat,Snack Foods,1998,Tier 3,Medium,Supermarket Type3,21811.87270,4.0
8520,DRE13,low fat,Soft Drinks,1998,Tier 3,Medium,Supermarket Type3,7817.43695,4.0
8521,FDT50,reg,Dairy,1998,Tier 3,Medium,Supermarket Type3,8833.23680,4.0
8522,FDM58,reg,Snack Foods,1998,Tier 3,Medium,Supermarket Type3,10130.95960,4.0

In [6]:
blinkit_data.tail(10)

,Item Identifier,Item Fat Content,Item Type,Outlet Establishment Year,Outlet Location Type,Outlet Size,Outlet Type,Total Amount,Rating
8513,DRY23,Regular,Soft Drinks,1998,Tier 3,Medium,Supermarket Type3,3872.73580,4.0
8514,FDA11,low fat,Baking Goods,1998,Tier 3,Medium,Supermarket Type3,8550.60990,4.0
8515,FDK38,low fat,Canned,1998,Tier 3,Medium,Supermarket Type3,13462.89935,4.0
8516,FDO38,low fat,Canned,1998,Tier 3,Medium,Supermarket Type3,7129.62365,4.0
8517,FDG32,low fat,Fruits and Vegetables,1998,Tier 3,Medium,Supermarket Type3,20069.54230,4.0
8518,NCT53,low fat,Health and Hygiene,1998,Tier 3,Medium,Supermarket Type3,14850.87215,4.0
8519,FDN09,low fat,Snack Foods,1998,Tier 3,Medium,Supermarket Type3,21811.87270,4.0
8520,DRE13,low fat,Soft Drinks,1998,Tier 3,Medium,Supermarket Type3,7817.43695,4.0
8521,FDT50,reg,Dairy,1998,Tier 3,Medium,Supermarket Type3,8833.23680,4.0
8522,FDM58,reg,Snack Foods,1998,Tier 3,Medium,Supermarket Type3,10130.95960,4.0

**Get the columns names of the data**

In [7]:
blinkit_data.columns

Index(['Item Identifier', 'Item Fat Content', 'Item Type',
       'Outlet Establishment Year', 'Outlet Location Type', 'Outlet Size',
       'Outlet Type', 'Total Amount', 'Rating'],
      dtype='object')

**Get the columns data types**

In [8]:
blinkit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Identifier            8523 non-null   object
 1   Item Fat Content           8523 non-null   object
 2   Item Type                  8523 non-null   object
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Location Type       8523 non-null   object
 5   Outlet Size                8523 non-null   object
 6   Outlet Type                8523 non-null   object
 7   Total Amount               8523 non-null   float64
 8   Rating                     8523 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 599.4+ KB

**Get the shape of data**

In [9]:
blinkit_data.shape

(8523, 9)

### **Clean Data If Required**

**Check for the missing values**

In [10]:
blinkit_data.isna().sum()

Item Identifier              0
Item Fat Content             0
Item Type                    0
Outlet Establishment Year    0
Outlet Location Type         0
Outlet Size                  0
Outlet Type                  0
Total Amount                 0
Rating                       0
dtype: int64

In [11]:
blinkit_data['Item Fat Content'].unique()

array(['Regular', 'Low Fat', 'low fat', 'LF', 'reg'], dtype=object)

In [12]:
blinkit_data['Item Fat Content'] = blinkit_data['Item Fat Content'].replace(
{'low fat' : 'Low Fat', 'LF' : 'Low Fat', 'reg' : 'Regular'})

In [13]:
blinkit_data['Item Fat Content'].unique()

array(['Regular', 'Low Fat'], dtype=object)

### **Simple Data Analysis**

**Find the total sales from all types of items sold**

In [14]:
total_sales = blinkit_data['Total Amount'].sum()
print("Total sales from all types of items sold:", round(total_sales, 2))

Total sales from all types of items sold: 108451753.64

In [15]:
print(f"Total sales from all types of items sold: $ {round(total_sales/1000000, 2)} M")

Total sales from all types of items sold: $ 108.45 M

In [16]:
print(f"Total sales from all types of items sold: ₹ {round(total_sales * 94.01/1000000 , 2)} M")

Total sales from all types of items sold: ₹ 10195.55 M

**Find the average sales from all types of items sold**

In [18]:
average_sales = blinkit_data['Total Amount'].mean()
print("Average sales from all types of items sold:", round(average_sales, 2))

Average sales from all types of items sold: 12724.6

In [20]:
print(f"Average sales from all types of items sold: $ {round(average_sales / 1000, 2)} K")

Average sales from all types of items sold: $ 12.72 K

**Find the total number of Transactions**

In [21]:
total_transactions = blinkit_data['Item Identifier'].count()
print(f"Total number of Transactions: {total_transactions}")

Total number of Transactions: 8523

In [23]:
print(f"Total number of Transactions: {round(total_transactions / 1000, 2)} K")

Total number of Transactions: 8.52 K

**Finding the average ratings of items sold**

In [24]:
average_rating = blinkit_data['Rating'].mean()
print(f"Average ratings of items sold: {round(average_rating, 2)}")

Average ratings of items sold: 3.97

### **Exploratory Data Analysis**

**EDA on Sales by Fat Content**

In [26]:
blinkit_data.groupby('Item Fat Content').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Total_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

,Total_Sales,Average_Sales,Total_Transactions,Average_Rating
Item Fat Content,,,,
Low Fat,70062850.98,12699.45,5517,3.97
Regular,38388902.67,12770.76,3006,3.97

**EDA on Sales by Item Type**

In [27]:
blinkit_data.groupby('Item Type').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Item Type,,,,
Baking Goods,7390999.96,11405.86,648,3.98
Breads,3192965.56,12720.98,251,3.88
Breakfast,1407601.87,12796.38,110,3.93
Canned,8186282.11,12613.69,649,3.99
Dairy,9140200.48,13402.05,682,3.97
Frozen Foods,10699939.05,12499.93,856,3.97
Fruits and Vegetables,16075698.31,13048.46,1232,3.96
Hard Drinks,2647454.56,12371.28,214,3.91
Health and Hygiene,6139331.95,11806.41,520,3.99
Household,12271881.42,13485.58,910,4.00
Meat,5365350.21,12624.35,425,4.02
Others,2026283.22,11989.84,169,3.95
Seafood,819277.77,12801.22,64,3.96
Snack Foods,15832911.32,13194.09,1200,3.95
Soft Drinks,5280903.39,11867.20,445,3.92
Starchy Foods,1974672.47,13342.38,148,3.92

**EDA on Sales by Outlet Location**

In [28]:
blinkit_data.groupby('Outlet Location Type').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Outlet Location Type,,,,
Tier 1,30359902.53,12713.53,2388,3.98
Tier 2,35481845.40,12740.34,2785,3.96
Tier 3,42610005.70,12719.40,3350,3.96

**EDA on Sales by Outlet Size**

In [29]:
blinkit_data.groupby('Outlet Size').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Outlet Size,,,,
High,22471490.46,12818.88,1753,3.95
Medium,45837589.49,12623.96,3631,3.98
Small,40142673.70,12788.36,3139,3.96

**EDA on Sales by Outlet Type**

In [30]:
blinkit_data.groupby('Outlet Type').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Outlet Type,,,,
Grocery Store,13712508.02,12661.60,1083,3.99
Supermarket Type1,71076377.28,12744.55,5577,3.96
Supermarket Type2,11865868.96,12786.50,928,3.97
Supermarket Type3,11796999.38,12617.11,935,3.95

**EDA on Sales by Fat Content and Item Type**

In [31]:
blinkit_data.groupby(['Item Fat Content', 'Item Type']).agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).round(2)

                                        Total_Sales  Average_Sales  \
Item Fat Content Item Type
Low Fat          Baking Goods            3578684.22       10877.46
                 Breads                  1700445.90       12146.04
                 Breakfast                611502.11       14914.69
                 Canned                  4294763.63       12594.61
                 Dairy                   5549877.11       13277.22
                 Frozen Foods            5645929.05       12546.51
                 Fruits and Vegetables   7764350.40       12324.37
                 Hard Drinks             2647454.56       12371.28
                 Health and Hygiene      6139331.95       11806.41
                 Household              12271881.42       13485.58
                 Meat                    2009848.91       11822.64
                 Others                  2026283.22       11989.84
                 Seafood                  379033.45       10244.15
                 Snack Foods             9773780.37       14123.96
                 Soft Drinks             4500625.18       12033.76
                 Starchy Foods           1169059.51       14256.82
Regular          Baking Goods            3812315.74       11950.83
                 Breads                  1492519.66       13446.12
                 Breakfast                796099.76       11537.68
                 Canned                  3891518.49       12634.80
                 Dairy                   3590323.37       13599.71
                 Frozen Foods            5054010.00       12448.30
                 Fruits and Vegetables   8311347.91       13806.23
                 Meat                    3355501.30       13158.83
                 Seafood                  440244.32       16305.35
                 Snack Foods             6059130.95       11927.42
                 Soft Drinks              780278.22       10989.83
                 Starchy Foods            805612.96       12206.26

                                        Number_Of_Transactions  Average_Rating
Item Fat Content Item Type
Low Fat          Baking Goods                              329            4.00
                 Breads                                    140            3.87
                 Breakfast                                  41            4.04
                 Canned                                    341            3.99
                 Dairy                                     418            3.97
                 Frozen Foods                              450            4.00
                 Fruits and Vegetables                     630            3.94
                 Hard Drinks                               214            3.91
                 Health and Hygiene                        520            3.99
                 Household                                 910            4.00
                 Meat                                      170            4.06
                 Others                                    169            3.95
                 Seafood                                    37            4.01
                 Snack Foods                               692            3.94
                 Soft Drinks                               374            3.93
                 Starchy Foods                              82            3.78
Regular          Baking Goods                              319            3.96
                 Breads                                    111            3.90
                 Breakfast                                  69            3.87
                 Canned                                    308            4.00
                 Dairy                                     264            3.96
                 Frozen Foods                              406            3.94
                 Fruits and Vegetables                     602            3.97
                 Meat                                      255            4.00
                 Seafood                                    27            3.89
                 Snack Foods                               508            3.97
                 Soft Drinks                                71            3.90
                 Starchy Foods                              66            4.09

**EDA on Sales by Top 5 Performing Item Types**

In [35]:
blinkit_data.groupby('Item Type').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).sort_values(by = 'Total_Sales', ascending = False).round(2).head()

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Item Type,,,,
Fruits and Vegetables,16075698.31,13048.46,1232,3.96
Snack Foods,15832911.32,13194.09,1200,3.95
Household,12271881.42,13485.58,910,4.00
Frozen Foods,10699939.05,12499.93,856,3.97
Dairy,9140200.48,13402.05,682,3.97

**EDA on Sales by Top 5 Outlets by Threir Establishment Year**

In [37]:
blinkit_data.groupby('Outlet Establishment Year').agg(
    Total_Sales = ('Total Amount', 'sum'),
    Average_Sales = ('Total Amount', 'mean'),
    Number_Of_Transactions = ('Item Identifier', 'count'),
    Average_Rating = ('Rating', 'mean')
).sort_values(by = 'Total_Sales', ascending = False).round(2).head()

,Total_Sales,Average_Sales,Number_Of_Transactions,Average_Rating
Outlet Establishment Year,,,,
1998,18458133.69,12616.63,1463,3.97
2017,12012627.61,12916.80,930,3.94
2010,11923231.62,12820.68,930,3.96
2000,11895763.66,12763.69,932,3.95
2022,11865868.96,12786.50,928,3.97